title: CUARC
author:
  name: Concordia University Amateur Radio Club
  email: info@cuarc.org
description: >
  Concordia University Amateur Radio Club

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"
  social_links:
    instagram: VE2RCU


header_pages:
  - about.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
theme: minima
